language: python
matrix:
  include:
    - python: 2.7
      env:
        - DJANGO_SETTINGS_MODULE=settings
install:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then pip install -U -r requirements/prod.txt; else pip install -U -r requirements/dev.txt; fi
before_script:
  - npm install phantomjs-prebuilt
  - export PHANTOMJS_PATH=`pwd`/node_modules/.bin/phantomjs
  - $PHANTOMJS_PATH --version
  - pip install python-coveralls selenium
  - python manage.py migrate
script:
  - py.test --pep8 --cov pdp
  - py.test tests/functional_tests.py
  - coveralls
