language: python
matrix:
  include:
    - python: 2.7
      env:
        - DJANGO_VERSION='<1.10'
        - DJANGO_SETTINGS_MODULE=pdp-site.settings
    - python: 2.7
      env:
        - DJANGO_VERSION='>=1.10'
        - DJANGO_SETTINGS_MODULE=pdp-site.settings
install:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then pip install -U -r requirements.txt; else pip install -U -r dev-requirements.txt; fi
before_script:
  - pip install python-coveralls selenium
  - pip install -U "Django$DJANGO_VERSION"
  # the following four tasks are only needed to run functional_tests.
  - python manage.py migrate
  # for firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - py.test --pep8 --cov pdp
  - py.test tests/functional_tests.py
  - coveralls
