language: python
python:
  - 2.7
  # - 3.5
env: DJANGO_SETTINGS_MODULE=pdp-site.settings
install: pip install -r requirements.txt
before_script:
  - pip install python-coveralls selenium
  # the following five tasks are only needed to run functional_tests.
  - python manage.py migrate
  - python manage.py runserver &
  # for firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - py.test --pep8 --cov pdp pdp
  # - py.test tests/functional_tests.py
  - coveralls
