#
# pdp install playbook
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10
  gather_facts: true
  remote_user: iamnsspr
  vars:
    app_name: pdp
    app_base: /data/local/django
    app_url_base: id
    local_base: ..

  roles:
    - apache_cluster
    - django

  tasks:
    - name: stat the secret file
      stat: path=/data/local/etc/pdp-secret
      register: secrets_stat

    - name: fail if no secret
      fail: msg="No secret file"
      when: not secrets_stat.stat.isreg or secrets_stat.stat.size < 8

    - name: copy pdp-access files
      template: "src=apache/pdp-access.xml dest=/data/conf/apache.conf.d/pdp-access.xml group=iam-dev mode=664"
      notify:
         - restart apache

    # testing non-prod environments, should probably get done another way if the tests
    # start getting longer
    - name: copy extra dev stuff
      copy: "src=../{{item}} dest={{app_base}}/pdp group=iam-dev mode=664 directory_mode=2775"
      with_items:
        - requirements-dev.txt
        - it
      when: cluster_type != "prod"

    - name: pip install dev
      pip: requirements={{ app_base }}/pdp/requirements-dev.txt virtualenv={{ app_base }}/pdp
      when: cluster_type != "prod"

    - name: run integration tests
      command: bin/py.test it
      environment:
        DJANGO_SETTINGS_MODULE: pdp-site.it_settings
      args:
        chdir: "{{ app_base }}/pdp"
      when: cluster_type != "prod"

    # always notify if we get all the way through in case we bombed out on a
    # prior run that would have notified.
    - name: notify restart apache
      command: /bin/true
      notify: restart apache
