#
# pdp install playbook
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10
  gather_facts: true
  remote_user: iamnsspr
  vars:
    app_name: pdp
    app_base: /data/local/django
    app_url_base: profile
    local_base: "{{playbook_dir}}/.."
    secrets_file: /data/local/etc/pdp-secret

  pre_tasks:
    - name: get version
      local_action: "shell python {{local_base}}/setup.py --version"
      register: version_cmd
    - set_fact: app_dir="{{app_base}}/{{app_name}}-{{version_cmd.stdout}}"

  roles:
    - apache_cluster
    - django

  tasks:
    # testing non-prod environments, should probably get done another way if the tests
    # start getting longer
    - name: copy extra dev stuff
      copy: "src={{local_base}}/{{item}} dest={{app_dir}} group=iam-dev mode=664 directory_mode=2775"
      with_items:
        - tests
      when: cluster_type != "prod"

    - name: run integration tests
      command: "venv/bin/pytest tests/integration_tests.py"
      environment:
        DJANGO_SETTINGS_MODULE: "settings.{{cluster_type}}"
      args:
        chdir: "{{ app_dir }}"
      when: cluster_type != "prod"

    # always notify if we get all the way through in case we bombed out on a
    # prior run that would have notified.
    - name: notify restart apache
      command: /bin/true
      notify: restart apache
