#
# pdp install playbook
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10

  tasks:

  - include_vars: "conf.yml"

  - name: copy app
    copy: "src=../{{item}} dest={{app_base}}/pdp group=iam-dev mode=664 directory_mode=2775"
    with_items:
      - manage.py
      - pdp
      - pdp-site
      - requirements.txt
      - setup.py

  - name: copy local settings
    copy: "src=../local_settings.py.{{ cluster_type }} dest={{app_base}}/pdp/pdp-site/local_settings.py group=iam-dev mode=664 "

  - name: verify libraries
    pip: requirements={{ app_base }}/pdp/requirements.txt virtualenv={{ app_base }}/pdp

  # update http and https config
  # change restarts apache
  - include: "tasks/apache_config.yml file=https prod=pdp"
  - include: "tasks/apache_config.yml file=http prod=pdp"
  - include: "tasks/apache_config.yml file=global prod=pdp"

  - name: verify db 
    file: "path={{ app_base }}/pdp/db state=directory group=iam-dev mode=2775"

  # setup db
  - name: check db 1
    stat: path={{app_base}}/pdp/db/db.sqlite3
    register: db_stat

  - name: check db 2
    django_manage: command=migrate app_path={{app_base}}/pdp python_path={{app_base}}/pdp virtualenv={{app_base}}/pdp
    when: db_stat.stat.exists == False

  - name: check db 3
    file: "path={{ app_base }}/pdp/db/db.sqlite3 state=file group=iam-dev mode=664"
    when: db_stat.stat.exists == False

  # run any handlers 
  - meta: flush_handlers


  # idle loadr if test fails
  - name: idle loadr on test fail
    command: /usr/bin/nohup /data/local/bin/ansible_command loadr idle
    when: "httest_result is defined and httest_result.rc != 0"
      
  # fail if test fails
  - name: fail on test fail
    fail: msg="API service test fails after install"
    when: "httest_result is defined and httest_result.rc != 0"

  handlers:
     - include: "tasks/iam_handlers.yml"

